#ifndef SPM22_ACCIARO_PROJECT_RUNTIME_STEPS_H
#define SPM22_ACCIARO_PROJECT_RUNTIME_STEPS_H

extern bool IS_UNIT_TEST_RUNNING;
extern bool IS_METRICS_RUNNING;

#endif //SPM22_ACCIARO_PROJECT_RUNTIME_STEPS_H
